-- seed.sql — dataset oficial de 50 medicamentos (Afirmative Pill)
-- Generado desde db/seed/medications.csv. Idempotente: se puede re-ejecutar.

insert into public.laboratories (name) values
  ('Abbott'),
  ('AstraZeneca'),
  ('Bayer'),
  ('Boehringer Ingelheim'),
  ('Genfar'),
  ('GlaxoSmithKline'),
  ('Grunenthal'),
  ('Janssen'),
  ('Laboratorios MK'),
  ('Lafrancol'),
  ('Merck'),
  ('Pfizer'),
  ('Roche'),
  ('Sandoz'),
  ('Sanofi'),
  ('Tecnoquímicas')
on conflict (name) do nothing;

insert into public.active_ingredients (name) values
  ('Aciclovir'),
  ('Alprazolam'),
  ('Amoxicilina + Ácido Clavulánico'),
  ('Atorvastatina'),
  ('Azitromicina'),
  ('Betametasona'),
  ('Budesonida'),
  ('Carvedilol'),
  ('Cefalexina'),
  ('Cetirizina'),
  ('Ciprofloxacino'),
  ('Claritromicina'),
  ('Clonazepam'),
  ('Clorfeniramina'),
  ('Dexametasona'),
  ('Diclofenaco'),
  ('Domperidona'),
  ('Enalapril'),
  ('Esomeprazol'),
  ('Fluconazol'),
  ('Furosemida'),
  ('Glibenclamida'),
  ('Hidroclorotiazida'),
  ('Hioscina'),
  ('Ibuprofeno'),
  ('Insulina Glargina'),
  ('Ketoconazol'),
  ('Lansoprazol'),
  ('Levofloxacino'),
  ('Levotiroxina'),
  ('Loratadina'),
  ('Losartán'),
  ('Meloxicam'),
  ('Metformina'),
  ('Metoprolol'),
  ('Miconazol'),
  ('Montelukast'),
  ('Naproxeno'),
  ('Omeprazol'),
  ('Paracetamol'),
  ('Prednisona'),
  ('Pregabalina'),
  ('Salbutamol'),
  ('Sales de Rehidratación Oral'),
  ('Sertralina'),
  ('Simvastatina'),
  ('Sucralfato'),
  ('Tramadol Clorhidrato'),
  ('Trimebutina'),
  ('Ácido Acetilsalicílico')
on conflict (name) do nothing;

insert into public.categories (name, slug) values
  ('Analgésicos', 'analgesicos'),
  ('Antibióticos', 'antibioticos'),
  ('Antihistamínicos', 'antihistaminicos'),
  ('Antiinflamatorios', 'antiinflamatorios'),
  ('Antimicóticos', 'antimicoticos'),
  ('Antivirales', 'antivirales'),
  ('Cardiovascular', 'cardiovascular'),
  ('Corticosteroides', 'corticosteroides'),
  ('Dermatológico', 'dermatologico'),
  ('Endocrinología', 'endocrinologia'),
  ('Gastrointestinal', 'gastrointestinal'),
  ('Pediatría / Sueros', 'pediatria-sueros'),
  ('Psiquiatría / Neuro', 'psiquiatria-neuro'),
  ('Respiratorio', 'respiratorio')
on conflict (name) do nothing;

insert into public.medications
  (sku, name, active_ingredient_id, category_id, laboratory_id, dosage, presentation, price, stock, requires_prescription, description)
select v.sku, v.name, ai.id, c.id, l.id, v.dosage, v.presentation, v.price, v.stock, v.requires_prescription, v.description
from (values
  ('MED-001', 'Acetaminofén Forte', 'Paracetamol', 'Analgésicos', 'Laboratorios MK', '500 mg', 'Caja x 20 tabletas', 9500::numeric, 120::integer, false, 'Alivio del dolor de cabeza y cuadros febriles leves a moderados.'),
  ('MED-002', 'Ibuprofeno Max', 'Ibuprofeno', 'Antiinflamatorios', 'Genfar', '800 mg', 'Caja x 30 tabletas', 18200::numeric, 85::integer, false, 'Antiinflamatorio no esteroideo para dolores articulares y musculares.'),
  ('MED-003', 'Amoxicilina Clavulanato', 'Amoxicilina + Ácido Clavulánico', 'Antibióticos', 'Sandoz', '875/125 mg', 'Caja x 14 tabletas', 46000::numeric, 40::integer, true, 'Antibiótico de amplio espectro para infecciones respiratorias bacterianas.'),
  ('MED-004', 'Loratadina Antiallerg', 'Loratadina', 'Antihistamínicos', 'Tecnoquímicas', '10 mg', 'Caja x 10 tabletas', 8900::numeric, 150::integer, false, 'Tratamiento sintomático de rinitis alérgica y urticaria crónica.'),
  ('MED-005', 'Omeprazol GastroProtect', 'Omeprazol', 'Gastrointestinal', 'Lafrancol', '20 mg', 'Caja x 28 cápsulas', 14500::numeric, 110::integer, false, 'Inhibidor de la bomba de protones para reflujo gástrico y úlceras.'),
  ('MED-006', 'Losartán Potásico', 'Losartán', 'Cardiovascular', 'Genfar', '50 mg', 'Caja x 30 tabletas', 16800::numeric, 95::integer, true, 'Antihipertensivo antagonista de los receptores de angiotensina II.'),
  ('MED-007', 'Metformina Clorhidrato', 'Metformina', 'Endocrinología', 'Merck', '850 mg', 'Caja x 30 tabletas', 21000::numeric, 75::integer, true, 'Hipoglucemiante oral para control de glucemia en diabetes tipo 2.'),
  ('MED-008', 'Atorvastatina Lipid', 'Atorvastatina', 'Cardiovascular', 'Pfizer', '20 mg', 'Caja x 30 tabletas', 32500::numeric, 60::integer, true, 'Regulador lipídico para reducir colesterol LDL y triglicéridos.'),
  ('MED-009', 'Cetirizina Dihidrocloruro', 'Cetirizina', 'Antihistamínicos', 'Bayer', '10 mg', 'Caja x 10 tabletas', 11200::numeric, 130::integer, false, 'Antihistamínico de segunda generación para cuadros alérgicos agudos.'),
  ('MED-010', 'Azitromicina Unidosis', 'Azitromicina', 'Antibióticos', 'Genfar', '500 mg', 'Caja x 3 tabletas', 28900::numeric, 50::integer, true, 'Macrólido indicado en infecciones del tracto respiratorio y piel.'),
  ('MED-011', 'Esomeprazol Dual', 'Esomeprazol', 'Gastrointestinal', 'AstraZeneca', '40 mg', 'Caja x 14 cápsulas', 39000::numeric, 45::integer, false, 'Tratamiento avanzado de esofagitis erosiva por reflujo gastroesofágico.'),
  ('MED-012', 'Clonazepam Sedafast', 'Clonazepam', 'Psiquiatría / Neuro', 'Roche', '2 mg', 'Caja x 30 tabletas', 27400::numeric, 25::integer, true, 'Benzodiacepina indicada en trastornos de pánico y crisis convulsivas.'),
  ('MED-013', 'Diclofenaco Sódico', 'Diclofenaco', 'Antiinflamatorios', 'Laboratorios MK', '50 mg', 'Caja x 20 tabletas', 12300::numeric, 105::integer, false, 'Analgésico antiinflamatorio para dolor agudo postraumático.'),
  ('MED-014', 'Sertralina Anxiofree', 'Sertralina', 'Psiquiatría / Neuro', 'Pfizer', '50 mg', 'Caja x 30 tabletas', 48500::numeric, 35::integer, true, 'Antidepresivo inhibidor selectivo de la recaptación de serotonina.'),
  ('MED-015', 'Salbutamol Aerosol HFA', 'Salbutamol', 'Respiratorio', 'GlaxoSmithKline', '100 mcg/dosis', 'Inhalador 200 dosis', 24900::numeric, 80::integer, false, 'Broncodilatador de acción rápida para crisis asmáticas y broncoespasmo.'),
  ('MED-016', 'Ciprofloxacino Bacterial', 'Ciprofloxacino', 'Antibióticos', 'Bayer', '500 mg', 'Caja x 10 tabletas', 26000::numeric, 42::integer, true, 'Fluoroquinolona de amplio espectro para infecciones urinarias complejas.'),
  ('MED-017', 'Hidroclorotiazida Diur', 'Hidroclorotiazida', 'Cardiovascular', 'Genfar', '25 mg', 'Caja x 30 tabletas', 9800::numeric, 90::integer, true, 'Diurético tiazídico coadyuvante en el manejo de la hipertensión arterial.'),
  ('MED-018', 'Naproxeno Sódico', 'Naproxeno', 'Antiinflamatorios', 'Bayer', '550 mg', 'Caja x 12 tabletas', 15400::numeric, 115::integer, false, 'Alivio potente del dolor inflamatorio osteomuscular y dental.'),
  ('MED-019', 'Dexametasona Depo', 'Dexametasona', 'Corticosteroides', 'Laboratorios MK', '4 mg/2 ml', 'Ampolla inyectable x 1', 8500::numeric, 65::integer, true, 'Corticoide sistémico potente para crisis alérgicas e inflamatorias severas.'),
  ('MED-020', 'Levotiroxina Sódica', 'Levotiroxina', 'Endocrinología', 'Abbott', '100 mcg', 'Caja x 50 tabletas', 31000::numeric, 70::integer, true, 'Hormona tiroidea sintética de reemplazo en hipotiroidismo primario.'),
  ('MED-021', 'Trimebutina Antispas', 'Trimebutina', 'Gastrointestinal', 'Sanofi', '200 mg', 'Caja x 30 tabletas', 34500::numeric, 55::integer, false, 'Regulador de la motilidad digestiva para síndrome de colon irritable.'),
  ('MED-022', 'Fluconazol Dermic', 'Fluconazol', 'Antimicóticos', 'Pfizer', '150 mg', 'Caja x 2 cápsulas', 19800::numeric, 85::integer, false, 'Antifúngico triazólico para candidiasis mucocutánea y sistémica.'),
  ('MED-023', 'Enalapril Maleato', 'Enalapril', 'Cardiovascular', 'Genfar', '20 mg', 'Caja x 30 tabletas', 11500::numeric, 100::integer, true, 'Inhibidor de la ECA para tratamiento de falla cardíaca e hipertensión.'),
  ('MED-024', 'Clorfeniramina Maleato', 'Clorfeniramina', 'Antihistamínicos', 'Laboratorios MK', '4 mg', 'Caja x 20 tabletas', 6500::numeric, 140::integer, false, 'Antihistamínico clásico para rinitis estacional y prurito alérgico.'),
  ('MED-025', 'Butilbromuro de Hioscina', 'Hioscina', 'Gastrointestinal', 'Boehringer Ingelheim', '10 mg', 'Caja x 10 grageas', 13800::numeric, 90::integer, false, 'Antiespasmódico visceral para cólicos abdominales y renales.'),
  ('MED-026', 'Tramadol Gotas', 'Tramadol Clorhidrato', 'Analgésicos', 'Grunenthal', '100 mg/ml', 'Frasco gotero 10 ml', 32000::numeric, 30::integer, true, 'Analgésico opioide atípico para dolor moderado a severo refractario.'),
  ('MED-027', 'Pregabalina Neuropain', 'Pregabalina', 'Psiquiatría / Neuro', 'Pfizer', '75 mg', 'Caja x 28 cápsulas', 56000::numeric, 45::integer, true, 'Modulador neuronal para neuropatía diabética y fibromialgia.'),
  ('MED-028', 'Lansoprazol Gastric', 'Lansoprazol', 'Gastrointestinal', 'Tecnoquímicas', '30 mg', 'Caja x 14 cápsulas', 22500::numeric, 65::integer, false, 'Inhibidor gástrico para cicatrización de úlcera duodenal activa.'),
  ('MED-029', 'Metoprolol Tartrato', 'Metoprolol', 'Cardiovascular', 'AstraZeneca', '50 mg', 'Caja x 30 tabletas', 14200::numeric, 80::integer, true, 'Betabloqueador selectivo para arritmias y cardiopatía isquémica.'),
  ('MED-030', 'Cefalexina Monohidrato', 'Cefalexina', 'Antibióticos', 'Laboratorios MK', '500 mg', 'Caja x 24 cápsulas', 33500::numeric, 50::integer, true, 'Cefalosporina de primera generación para infecciones de piel y tejidos.'),
  ('MED-031', 'Aciclovir Dermacare', 'Aciclovir', 'Antivirales', 'Genfar', '0.05', 'Tubo crema x 15 g', 16700::numeric, 75::integer, false, 'Antiviral tópico específico para herpes simple labial y genital inicial.'),
  ('MED-032', 'Insulina Glargina Pen', 'Insulina Glargina', 'Endocrinología', 'Sanofi', '100 UI/ml', 'Pluma precargada 3 ml', 89000::numeric, 20::integer, true, 'Análogo de insulina de acción ultraprolongada para diabetes mellitus.'),
  ('MED-033', 'Meloxicam Flex', 'Meloxicam', 'Antiinflamatorios', 'Laboratorios MK', '15 mg', 'Caja x 10 tabletas', 17900::numeric, 90::integer, false, 'Antiinflamatorio preferencial COX-2 para osteoartritis y artritis.'),
  ('MED-034', 'Alprazolam Calmpill', 'Alprazolam', 'Psiquiatría / Neuro', 'Pfizer', '0.5 mg', 'Caja x 30 tabletas', 29000::numeric, 25::integer, true, 'Tranquilizante menor para crisis de angustia y ansiedad generalizada.'),
  ('MED-035', 'Budesonida PulmoInhaler', 'Budesonida', 'Respiratorio', 'AstraZeneca', '200 mcg/dosis', 'Inhalador 200 dosis', 49500::numeric, 40::integer, true, 'Corticoide inhalado para control de mantenimiento en asma persistente.'),
  ('MED-036', 'Carvedilol HeartCare', 'Carvedilol', 'Cardiovascular', 'Roche', '25 mg', 'Caja x 30 tabletas', 24000::numeric, 60::integer, true, 'Betabloqueador no selectivo vasodilatador en insuficiencia cardíaca.'),
  ('MED-037', 'Furosemida Renal', 'Furosemida', 'Cardiovascular', 'Genfar', '40 mg', 'Caja x 30 tabletas', 8700::numeric, 110::integer, true, 'Diurético de asa de alta potencia para edemas periféricos y pulmonares.'),
  ('MED-038', 'Ketoconazol Medipill', 'Ketoconazol', 'Antimicóticos', 'Janssen', '0.02', 'Frasco champú 120 ml', 28500::numeric, 50::integer, false, 'Tratamiento antimicótico para dermatitis seborreica y pitiriasis.'),
  ('MED-039', 'Montelukast Broncho', 'Montelukast', 'Respiratorio', 'Merck', '10 mg', 'Caja x 30 tabletas', 44000::numeric, 55::integer, false, 'Antagonista de receptores de leucotrienos para prevención asmática.'),
  ('MED-040', 'Prednisona Immunocort', 'Prednisona', 'Corticosteroides', 'Laboratorios MK', '20 mg', 'Caja x 30 tabletas', 22000::numeric, 70::integer, true, 'Inmunosupresor y antiinflamatorio esteroideo sistémico de rescate.'),
  ('MED-041', 'Domperidona Gastrofluid', 'Domperidona', 'Gastrointestinal', 'Sanofi', '10 mg', 'Caja x 20 tabletas', 15800::numeric, 80::integer, false, 'Procinético y antiemético para náuseas y vaciamiento gástrico lento.'),
  ('MED-042', 'Claritromicina Protect', 'Claritromicina', 'Antibióticos', 'Abbott', '500 mg', 'Caja x 10 tabletas', 41000::numeric, 35::integer, true, 'Antibiótico macrólido coadyuvante en erradicación de H. pylori.'),
  ('MED-043', 'Simvastatina Stat', 'Simvastatina', 'Cardiovascular', 'Genfar', '20 mg', 'Caja x 30 tabletas', 13500::numeric, 90::integer, true, 'Estatina para control primario de dislipidemias e hipercolesterolemia.'),
  ('MED-044', 'Ácido Acetilsalicílico Cardio', 'Ácido Acetilsalicílico', 'Cardiovascular', 'Bayer', '100 mg', 'Caja x 30 tabletas', 11000::numeric, 160::integer, false, 'Antiagregante plaquetario profiláctico para eventos cardiovasculares.'),
  ('MED-045', 'Miconazol Crema Vag', 'Miconazol', 'Antimicóticos', 'Genfar', '0.02', 'Tubo crema x 40 g + aplicadores', 21500::numeric, 45::integer, false, 'Antimicótico ginecológico local para vulvovaginitis fúngica.'),
  ('MED-046', 'Glibenclamida Diabet', 'Glibenclamida', 'Endocrinología', 'Laboratorios MK', '5 mg', 'Caja x 30 tabletas', 9200::numeric, 85::integer, true, 'Sulfonilurea estimulante de secreción de insulina pancreática.'),
  ('MED-047', 'Betametasona Valerato', 'Betametasona', 'Dermatológico', 'Genfar', '0.001', 'Tubo crema x 30 g', 14900::numeric, 70::integer, true, 'Corticosteroide dermatológico tópico para dermatosis inflamatorias.'),
  ('MED-048', 'Sucralfato Gastromucosa', 'Sucralfato', 'Gastrointestinal', 'Laboratorios MK', '1 g', 'Caja x 20 sobres granulado', 37500::numeric, 40::integer, false, 'Citoprotector gástrico de barrera mecánica sobre úlceras pépticas.'),
  ('MED-049', 'Levofloxacino Bactrimax', 'Levofloxacino', 'Antibióticos', 'Sanofi', '750 mg', 'Caja x 7 tabletas', 58000::numeric, 30::integer, true, 'Quinolona respiratoria de alta dosis para neumonía bacteriana adquirida.'),
  ('MED-050', 'Electrolitos Orales Pediátricos', 'Sales de Rehidratación Oral', 'Pediatría / Sueros', 'Abbott', 'Electrolitos balanceados', 'Frasco x 500 ml solución oral', 8500::numeric, 120::integer, false, 'Rehidratación oral para prevención de deshidratación por diarrea o vómito.')
) as v (sku, name, ingredient, category, laboratory, dosage, presentation, price, stock, requires_prescription, description)
join public.active_ingredients ai on ai.name = v.ingredient
join public.categories         c  on c.name  = v.category
join public.laboratories       l  on l.name  = v.laboratory
on conflict (sku) do nothing;
